baseurl = "https://rodogi.github.io/" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "rodrigo dorantes-gilardi" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating
# copyright = "Copyright &copy; Copyright Owner. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices

# Controls default theme and theme components
theme = [
  "fractal-forest", # OBSD
  "after-dark" # AGPL-3.0-or-later
]

disableLiveReload = true # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file

pygmentsCodefences = true # Suggested, highlight fenced code blocks
pygmentsUseClasses = true # Required for custom syntax highlighting

sectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "Personal blog of Rodrigo Dorantes-Gilardi" # Suggested, controls default description meta
  author = "Rodrigo Dorantes-Gilardi" # Optional, controls author name display on posts
  show_menu = true
  powered_by = false
  hide_author = false # Optional, set true to hide author name on posts
  disable_csp = false # Optional, set true to disable content security policy
  images = [
    "https://source.unsplash.com/collection/983219/2000x1322"
  ] # Suggested, controls default Open Graph images
  highlight = true
  highlightStyle = "solarized-dark"
  highlightLanguages = ["r", "python", "bash"]

[params.hackcss]
  palette = "standard"

[params.layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[params.layout.footer]
  hidden = true # Optional, set true to hide footer

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

[[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "post"
    url = "/post"

[[menu.main]]
    name = "Resume"
    weight = 3
    identifier = "resume"
    url = "/resume"

[permalinks]
  post = "/:title/"